export const COUNTRIES = [
  { code: 'ALL', country: 'All' },
  { code: 'AU', country: 'Australia' },
  { code: 'US', country: 'United States' },
  { code: 'GB', country: 'United Kingdom' },
  { code: 'CA', country: 'Canada' },
  { code: 'IN', country: 'India' },
  { code: 'CN', country: 'China' },
  { code: 'AR', country: 'Argentina' },
  { code: 'AT', country: 'Austria' },
  { code: 'BH', country: 'Bahrain' },
  { code: 'BD', country: 'Bangladesh' },
  { code: 'BE', country: 'Belgium' },
  { code: 'BM', country: 'Bermuda' },
  { code: 'BW', country: 'Botswana' },
  { code: 'BR', country: 'Brazil' },
  { code: 'BG', country: 'Bulgaria' },
  { code: 'CL', country: 'Chile' },
  { code: 'CO', country: 'Colombia' },
  { code: 'HR', country: 'Croatia' },
  { code: 'CY', country: 'Cyprus' },
  { code: 'CZ', country: 'Czech Republic' },
  { code: 'DK', country: 'Denmark' },
  { code: 'EG', country: 'Egypt' },
  { code: 'EE', country: 'Estonia' },
  { code: 'FI', country: 'Finland' },
  { code: 'FR', country: 'France' },
  { code: 'DE', country: 'Germany' },
  { code: 'GH', country: 'Ghana' },
  { code: 'GR', country: 'Greece' },
  { code: 'HK', country: 'Hong Kong' },
  { code: 'HU', country: 'Hungary' },
  { code: 'IS', country: 'Iceland' },
  { code: 'ID', country: 'Indonesia' },
  { code: 'IE', country: 'Ireland' },
  { code: 'IL', country: 'Israel' },
  { code: 'IT', country: 'Italy' },
  { code: 'CI', country: 'Ivory Coast' },
  { code: 'JM', country: 'Jamaica' },
  { code: 'JP', country: 'Japan' },
  { code: 'JO', country: 'Jordan' },
  { code: 'KZ', country: 'Kazakhstan' },
  { code: 'KE', country: 'Kenya' },
  { code: 'KW', country: 'Kuwait' },
  { code: 'LV', country: 'Latvia' },
  { code: 'LT', country: 'Lithuania' },
  { code: 'LU', country: 'Luxembourg' },
  { code: 'MW', country: 'Malawi' },
  { code: 'MY', country: 'Malaysia' },
  { code: 'MT', country: 'Malta' },
  { code: 'MU', country: 'Mauritius' },
  { code: 'MX', country: 'Mexico' },
  { code: 'MA', country: 'Morocco' },
  { code: 'NA', country: 'Namibia' },
  { code: 'NL', country: 'Netherlands' },
  { code: 'NZ', country: 'New Zealand' },
  { code: 'NG', country: 'Nigeria' },
  { code: 'NO', country: 'Norway' },
  { code: 'OM', country: 'Oman' },
  { code: 'PK', country: 'Pakistan' },
  { code: 'PS', country: 'Palestinian Authority' },
  { code: 'PE', country: 'Peru' },
  { code: 'PH', country: 'Philippines' },
  { code: 'PL', country: 'Poland' },
  { code: 'PT', country: 'Portugal' },
  { code: 'QA', country: 'Qatar' },
  { code: 'RO', country: 'Romania' },
  { code: 'RU', country: 'Russia' },
  { code: 'SA', country: 'Saudi Arabia' },
  { code: 'RS', country: 'Serbia' },
  { code: 'SG', country: 'Singapore' },
  { code: 'SK', country: 'Slovakia' },
  { code: 'SI', country: 'Slovenia' },
  { code: 'ZA', country: 'South Africa' },
  { code: 'KR', country: 'South Korea' },
  { code: 'ES', country: 'Spain' },
  { code: 'LK', country: 'Sri Lanka' },
  { code: 'SE', country: 'Sweden' },
  { code: 'CH', country: 'Switzerland' },
  { code: 'TW', country: 'Taiwan' },
  { code: 'TZ', country: 'Tanzania' },
  { code: 'TH', country: 'Thailand' },
  { code: 'TT', country: 'Trinidad & Tobago' },
  { code: 'TN', country: 'Tunisia' },
  { code: 'TR', country: 'Turkey' },
  { code: 'UG', country: 'Uganda' },
  { code: 'UA', country: 'Ukraine' },
  { code: 'AE', country: 'United Arab Emirates' },
  { code: 'VE', country: 'Venezuela' },
  { code: 'VN', country: 'Vietnam' },
  { code: 'ZM', country: 'Zambia' },
  { code: 'ZW', country: 'Zimbabwe' },
];
